local chain = require("chain")

describe("Chain:filter()", function()

    it("should filter List elements based on a predicate function", function()
        chain({10, 20, 30, 40})
            :filter(function(v) return v % 20 == 0 end)
            :values():assertEquals({20, 40})
    end)

    it("should filter Dict elements based on a predicate function", function()
        chain({a = 10, b = 20, c = 30, d = 40})
            :filter(function(v) return v % 20 == 0 end)
            :assertEquals({b = 20, d = 40})
    end)

    it("should pass key to the predicate function", function()
        chain({a = 10, b = 20, c = 30, d = 40})
            :filter(function(v, k) return v > 15 and k ~= "d" end)
            :assertEquals({b = 20, c = 30})
    end)

    it("should pass key and index to the predicate function", function()
        chain({a = 10, b = 20, c = 30, d = 40})
            :filter(function(v, k, idx) return v > 15 and k ~= "d" and idx ~= 3 end)
            :assertEquals({b = 20})
    end)

    it("should return an empty chain if no elements match the predicate", function()
        chain({1, 3, 5})
            :filter(function(v) return v % 2 == 0 end)
            :values():assertEquals({})
    end)

    it("should return an empty chain if the input chain is empty", function()
        chain({})
            :filter(function(v) return v % 2 == 0 end)
            :assertEquals({})
    end)

    it("should preserve the original order of elements that pass the filter", function()
         chain({5, 2, 8, 1, 4, 7})
             :filter(function(v) return v > 3 end)
             :values():assertEquals({5, 8, 4, 7})
    end)

    it("should throw an error when predicate is not a function", function()
        expect(function()
            chain({}):filter()
        end).to.fail("filter(pred): pred must be a function (got nil)")
        expect(function()
            chain({}):filter(-1)
        end).to.fail("filter(pred): pred must be a function (got number: -1)")
        expect(function()
            chain({}):filter("not_a_function")
        end).to.fail("filter(pred): pred must be a function (got string: 'not_a_function')")
    end)
end)
